DROP TRIGGER IF EXISTS stations_insert ON stations;
--;;
DROP TRIGGER IF EXISTS stations_update ON stations;
--;;
DROP TABLE IF EXISTS stations CASCADE;
--;;
DROP SEQUENCE IF EXISTS station_ids;
--;;
DROP FUNCTION on_record_insert() CASCADE;
--;;
DROP FUNCTION on_record_update() CASCADE;
