DROP TRIGGER IF EXISTS trips_insert ON trips;
--;;
DROP TRIGGER IF EXISTS trips_update ON trips;
--;;
DROP TRIGGER IF EXISTS hops_insert ON hops;
--;;
DROP TRIGGER IF EXISTS hops_update ON hops;
--;;
DROP TABLE IF EXISTS hops CASCADE;
--;;
DROP TABLE IF EXISTS trips CASCADE;
--;;
DROP SEQUENCE IF EXISTS trip_ids;
--;;
DROP SEQUENCE IF EXISTS hop_ids;
